- hosts: all
  become: yes
  tasks:
    - name: update
      apt: 
        update_cache: yes

    - name: Install apache2
      apt: 
        name: apache2
        state: latest

    - name: restart apache2
      service: 
        name: apache2 
        state: started

    - name: Check apache2 configuration
      command: apachectl configtest
      ignore_errors: yes

    - name: restart apache2
      service: 
      name: apache2 
        state: restarted
        enabled: yes

    - name: Check apache2 configuration
      command: apachectl configtest
      ignore_errors: yes

    - name: restart apache2
      service: 
        name: apache2 
        state: restarted
        enabled: yes
